
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lafyktdjzskzwqfzciyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhZnlrdGRqenNrendxZnpjaXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDUxMzEsImV4cCI6MjA2MDMyMTEzMX0.nGb8KLlQsE5PXWVhCL2zSuVp9ZapxLuO1w4115fqKFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
